spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      max-lifetime: 290000        # 커넥션 최대 수명 (약 4.8분)
      keepalive-time: 120000      # 2분마다 연결 살아있는지 확인
      connection-timeout: 10000   # 연결 못 얻으면 10초 후 포기

  jpa:
    show-sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  elasticsearch:
    uris: http://${ELASTICSEARCH_HOST}:9200

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
